### ISSUE TITLE
`no-commit-to-branch` hook is not validating properly the regex

### ISSUE THREAD

**Issue by maurizio-cacace** [pre-commit/pre-commit-hooks#1017]
i'm using `no-commit-to-branch` hook with `rev: v4.5.0`.

the expression is:

```
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: no-commit-to-branch       
        args: ['--pattern', '^(dependabot\/|updatecli_)?[0-9A-Za-z][0-9A-Za-z_-]{1,32}$']
```

but using a branch name like: `XXX-1271-bad.branch.name` it pass:

`don't commit to branch...................................................Passed`

but it should fail the pre-commit hook because it contains dots (.), which are not allowed according to the regex pattern mentioned.
The regex expression is valid because I tested it in bash script using gha pipeline and it is failing the check.

Do you have any suggestions?

thanks in advance
