### ISSUE TITLE
`pretty-format-json` using the flag `--indent` completely breaks json files w/o warning

### ISSUE THREAD

**Issue by Avasam** [pre-commit/pre-commit-hooks#1021]
`pre-commit-hooks` config in `.pre-commit-config.yaml`:
```
repos:
  # Various useful generic autofixes
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: check-case-conflict
      - id: check-merge-conflict
      # JSON formatting. Prettier's unwrapping is undesirable
      - id: pretty-format-json
        args: [--autofix, --no-ensure-ascii, --no-sort-keys, --indent] # add as many space as you want after --indent
```

Example file change
![image](https://github.com/pre-commit/pre-commit-hooks/assets/1350584/c775c99e-49e1-44b8-b0ac-756a1f00ac1c)
