### ISSUE TITLE
except case for `double-quote-string-fixer`

### ISSUE THREAD

**Issue by emcek** [pre-commit/pre-commit-hooks#1022]
Hi,
Question, using hook: `double-quote-string-fixer` can I add exception to it?

I got one file in repository with is change by external program (during manual testing) to using double-quotes, so pre-commint and this soft constantly race and change back and fore `' <-> "`

**Comment by asottile** [comment]
what have you tried?

**Comment by emcek** [comment]
I mean... how can I do that, except file from hook?

**Comment by asottile** [comment]
yes but what have you tried to accomplish that -- have you read the docs?

**Comment by emcek** [comment]
```
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: debug-statements
      - id: double-quote-string-fixer
        exclude: 'qtgui_rc.py'
      - id: check-toml
      - id: check-yaml
      - id: check-json
      - id: requirements-txt-fixer
      - id: fix-byte-order-marker
```
this throw a bunch of errors....
