### ISSUE TITLE
proposal: generic subprocess

### ISSUE THREAD

**Issue by ericfrederich** [pre-commit/pre-commit-hooks#1037]
I'm happy to implement this if it is acceptable.

I think it would be useful to be able to run subprocess specified by the configuration against files.

I thought of this idea because currently the `pre-commit-terraform` hooks are implemented in Bash which is fine for Linux systems, or Windows if you're using WSL or Git Bash, but it fails from powershell or a regular command prompt.
I'm working with them to [port hooks from bash to Python](https://github.com/antonbabenko/pre-commit-terraform/pull/652) (since pre-commit is Python based anyway).

While I wait for this PR to maybe get accepted, I was thinking it would be nice if this `pre-commit-hooks` repo had a hook where you could just specify a generic command.

Maybe it could behave similar to something like Bash's [xargs](https://man7.org/linux/man-pages/man1/xargs.1.html).  Maybe even give the hook the id of `xargs`?

Example:

```yaml
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: vX.Y.Z
    hooks:
    # run terraform fmt against all .tf and .tfvars files
    -   id: xargs
        args: ["terraform", "fmt"]
        files: \.tf(vars)?$
        exclude: \.terraform/.*$
```

**Comment by asottile** [comment]
is that not what `repo: local` let's you do?

**Comment by ericfrederich** [comment]
Ah, nice, thanks... `repo: local` and `language: system`

```yaml
- repo: local
  hooks:
  - id: terraform_fmt
    name: Terraform fmt
    description: Rewrites all Terraform configuration files to a canonical format.
    entry: terraform fmt
    language: system
    files: (\.tf|\.tfvars)$
    exclude: \.terraform/.*$
```
