### ISSUE TITLE
Configure pylint rules for custom python pre-commit

### ISSUE THREAD

**Issue by MHoinkaBS** [pre-commit/pre-commit-hooks#1107]
Hi 
I have a Python script to validate whether the required directories are in the repository. I want to run it as a pre-commit.  
In the script, I use fstrings both for logging and for concatenating paths, for example: 
`logging.debug(f"Projects root dirs: {root_dirs}")`

My local .pylintrc has been modified:     
`logging-modules=fstr` and is ok with the whole script.
Black also says it's OK. 

But when I've added it to my pre-commit-config and run it locally it returned: 
```
$ pre-commit run validate-env-dirs --all-files
validate-env-dirs........................................................Failed
- hook id: validate-env-dirs
- exit code: 1

File "./check_envs.py", line 51
    logging.debug(f"Projects root dirs: {root_dirs}")
                                                   ^
SyntaxError: invalid syntax

``` 

When I switch to lazy formatting:  `logging.debug("Projects root dirs: %root_dirs", root_dirs)`
 it is ok in this line of code.  Using .format() is also fine.

My pre-commit-config.yaml looks as follow: 

```
repos: 
- repo: local
  hooks:
    - id: validate-env-dirs
      name: validate-env-dirs
      entry: ./check_envs.py
      language: python
      language_version: python3.10
      types: [python]
      pass_filenames: false
``` 

So, I assume  
somewhere underneath pre-commit a pylint is called but with default 'logging-modules=old` config. Not to mention error message seems a bit ambiguous.   

Please help me with how can I change the behaviour or disable this linting. Haven't found any clues in the docs yet
