### ISSUE TITLE
flake8 ignores --config args

### ISSUE THREAD

**Issue by dwaynebailey** [pre-commit/pre-commit-hooks#112]
With the following config

```yaml
    -   id: flake8
        args: ['--config=setup.cfg']
```

Any settings in `setup.cfg` are never read.  Adding additional settings e.g. `args: ['--config=setup.cfg', '--max-line-length=500']` will set max line length to 500 but will ignore anything set in `setup.cfg`.

**Comment by asottile** [comment]
This is almost certainly a bug in flake8 itself.  We simply wrap the executable.

Do you see the same results when calling `flake8 --config=setup.cfg file1.py file2.py file3.py`

Which setting is flake8 not respecting?

flake8 bug reports can go here: https://gitlab.com/pycqa/flake8

**Comment by dwaynebailey** [comment]
@asottile thanks for the quick response.  Seems you are spot on.

`exclude` and `ignore` are not being used when `pre-commit` runs. But `max-line-length` is read from `setup.cfg`.  So some settings are being read from the configuration.

File based running seems to be the problem.  In `setup.cfg::exclude` I exclude `migrations`

Running `flake8 --config=setup.cfg myapp/migrations/` works but `flake8 --config=setup.cfg myapp/migrations/0001_initial.py`

I'll report upstream, just giving the diagnosis to help others.

**Comment by asottile** [comment]
Ah yes I've found this as well.

If you have this config:

```
[flake8]
exclude = foo/
```

and you run `flake8 foo/bar.py` it'll still try and lint `foo/bar.py`

What we've been doing in our repos is not using flake8's exclude but instead use pre-commit's exclude:

```yaml
   -  id: flake8
      exclude: ...
```

**Comment by dwaynebailey** [comment]
Here is the upstream bug https://gitlab.com/pycqa/flake8/issues/10 closed as WONTFIX.

**Comment by asottile** [comment]
unfortunate!  well, doing it through .pre-commit-config.yaml'll work either way

**Comment by dwaynebailey** [comment]
It will also selectively ignore and choose some of your other settings so something more like this should work:

```yml
    -   id: flake8
        args: ['--config=setup.cfg', '--ignore=E129,E2']
        exclude: ...
```

**Comment by Smarandii** [comment]
This works for me:

```yaml
...
  - repo: https://github.com/PyCQA/flake8
    rev: 7.2.0
    hooks:
      - id: flake8
        entry: flake8 --ignore E501,F401
        additional_dependencies:
          - flake8-picky-parentheses
          - flake8-return
          - flake8-comprehensions
        args: ['path_to_your_code']
```
