### ISSUE TITLE
check-added-large-files broken (5.0.0)

### ISSUE THREAD

**Issue by ReXtrem** [pre-commit/pre-commit-hooks#1128]
I updated the hook to version 5.0.0 was before:
```
- repo: https://github.com/pre-commit/pre-commit-hooks.git
  rev: v4.6.0
```

**Command used:**
`pre-commit run    `

**Error:**
An error has occurred: InvalidManifestError: 
==> File /Users/admin.cache/pre-commit/repox6vmoc76/.pre-commit-hooks.yaml
==> At Hook(id='check-added-large-files')
==> At key: stages
==> At index 0
=====> Expected one of commit, commit-msg, manual, merge-commit, post-checkout, post-commit, post-merge, post-rewrite, prepare-commit-msg, push but got: 'pre-commit'
Check the log at /Users/admin/.cache/pre-commit/pre-commit.log

**Current .pre-commit-config.yaml:**

```
default_language_version:
  python: python3

repos:
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks.git
  rev: v2.13.0
  hooks:
  - id: pretty-format-java
    name: Google Java Formatter
    description: Runs Google Java Formatter over Java source files
    entry: pretty-format-java
    language: python
    types: [java]
    require_serial: true
    minimum_pre_commit_version: '1'
    args: [--autofix, --google-java-formatter-version=1.17.0]
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2', --preserve-quotes]
- repo: https://github.com/pre-commit/pre-commit-hooks.git
  rev: v5.0.0
  hooks:
  - id: check-added-large-files
  - id: check-xml
  - id: check-yaml
    args: [--unsafe]
  - id: check-json
  - id: check-merge-conflict
  - id: check-case-conflict
  - id: mixed-line-ending
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: no-commit-to-branch
```

Feature seems to be broken now.
