### ISSUE TITLE
The trailing-whitespaces hook markdown-linebreak-ext parameter should also accept multi stage extentions

### ISSUE THREAD

**Issue by FormindAPE** [pre-commit/pre-commit-hooks#1143]
On a project where I use jinja2 I have encountered the following issue:

I have 2 kinds of jinja template files :
- json that uses `json.j2` extention (example `data.json.j2`)
- markdown that use `md.j2` extention (example `template.md.j2`)

I allso use plain makdown file with `md` extentions.

but currently if I use the folowing configuration:
```
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    - id: trailing-whitespace
      args: ['--markdown-linebreak-ext=md,md.j2']
```
I have this error :
```
usage: trailing-whitespace-fixer [-h]
                                 [--markdown-linebreak-ext *|EXT[,EXT,...]]
                                 [--chars CHARS]
                                 [filenames ...]
trailing-whitespace-fixer: error: bad --markdown-linebreak-ext extension '.md.j2' (has . / \ :)
  (probably filename; use '--markdown-linebreak-ext=EXT')
```

one possible solution  could be the following :
1) removing the check of `.` 
2) create an array of md suffixes (in my context, it will result in `[['.md'],['.md','.j2']]`
3) change the system to get an extension using paslib (`suffixes` property  of class `PurePathBase`)
4) change `md = all_markdown or extension in md_exts` to `md = all_markdown or extensions in md_suffixes`
