### ISSUE TITLE
Someone knows a hook using pre-commit to run nosetests/nose2?

### ISSUE THREAD

**Issue by ryukinix** [pre-commit/pre-commit-hooks#115]
Would really great for me. I appreciate the attention and the awesome tool. Managing hooks never will be easy as is with this tool.

**Comment by asottile** [comment]
This might be a good opportunity for [repository local hooks](http://pre-commit.com/#repository-local-hooks).

Maybe something like:

```yaml
repo: local
hooks:
    -   id: nosetests
        name: nosetests
        entry: nose2
        language: system
        always_run: true
```

**Comment by ryukinix** [comment]
Well, I only put this in my `.yml` file and solves magically?

**Comment by asottile** [comment]
Yeah if it works for you :)

**Comment by ryukinix** [comment]
Nice is almost working for me, but I need force the execution on the root of git repository to get properly the tests running. How I can ignore the arguments passed on file-match? 

### my pre-commit hook entry
```yaml
- repo: local
  hooks:
  - id: nosetests
    name: nosetests
    entry: nose2
    language: system
    files: \.py$
```

## execution
```python-tracabeck
[lerax@starfox decorating (master)]$ pre-commit run nosetests
nosetests................................................................Failed
hookid: nosetests

E
======================================================================
ERROR: decorating/animation.py (nose2.loader.LoadTestsFailure)
----------------------------------------------------------------------
ImportError: No module named 'decorating/animation'

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
``` 

### my tree project:
```
[lerax@starfox decorating (master)]$ tree --sort=size
.
├── decorating
│   ├── animation.py
│   ├── general.py
│   ├── color.py
│   └── __init__.py
├── docs
├── tests
│   ├── test_general.py
│   ├── test_animated.py
│   └── __main__.py
├── Makefile
├── codecov.yml
├── setup.py
├── README.md
├── CHANGELOG
├── TODO
├── LICENSE
├── MANIFEST.in
└── requirements.txt

```
