### ISSUE TITLE
hook for image optimization

### ISSUE THREAD

**Issue by jab** [pre-commit/pre-commit-hooks#232]
It's all too easy for developers and designers to forget to manually run e.g. `pngcrush` (or `optipng`, etc.) on every added/modified png before committing. (Same of course goes for jpg's, svg's, etc.) I was surprised to find no out-of-the-box hooks for image optimization. Is there any interest in adding this? If so I'd be happy to take a crack at a PR if no one else beats me to it.

ref: http://blog.javabien.net/2010/03/28/crush-png-images-at-commit-time-with-git/

Thanks for the great work on pre-commit!

**Comment by asottile** [comment]
Thanks for the issue :)

We've definitely had some thoughts about image manipulation at commit time -- I happen to know that yelp has some closed source pre-commit hooks for optimizing pngs, jpegs, and svgs -- but unfortunately they haven't open sourced them yet.  @chriskuehl @thebostik

The linked article is pretty easy to implement in pre-commit as well -- there's a couple choices:

### as a `script` hook assuming that `pngcrush` is installed

Something like this:

```bash
#!/usr/bin/env bash
# pngcrush only takes one argument at a time, use `-ow` to in-place modify
xargs -I{} <<< "$@" pngcrush -rem allb -brute -reduce -ow {}
```
With a configuration like:

```yaml
-   id: pngcrush-system
    name: pngcrush
    language: script
    entry: pngcrush.sh
    types: [png]
```

### as a `docker` hook (probably more universally useful

(use the same script as above)

```dockerfile
FROM ubuntu:xenial
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        pngcrush && \
    apt-get clean
ADD pngcrush.sh /usr/local/bin/pngcrush.sh
```

With a configuration file like

```yaml
-   id: pngcrush
    name: pngcrush
    language: docker
    entry: pngcrush.sh
    types: [png]
```

### as a local hook

This *could* even be implemented without a repository, it's not pretty and not super portable but:

```yaml
-   repo: local
    hooks:
    -   id: pngcrush
        name: pngcrush
        language: system
        entry: bash -c 'xargs -I{} <<< "$@" pngcrush -rem allb -brute -reduce -ow {}'
        types: [png]
```

### _Note: I haven't tested any of these, they're just some (hopefully) useful sketches to get you started on how you'd go about implementing this_
