### ISSUE TITLE
pre-commit might install flake8 unpinned?

### ISSUE THREAD

**Issue by mittonk** [pre-commit/pre-commit-hooks#247]
I'm seeing the same version of code pass or fail flake8 checks on different machines.
All use the same version of code, same `.pre-commit-config.yaml`, same version of `pre-commit` (v1.0.0), and have pinned the same version of `flake8` (3.4.1).  Some pass flake8 checks, some correctly find an E722:

```
Tests should end in _test.py.............................................Passed
Flake8...................................................................Failed
hookid: flake8

testing/factories/base_factory.py:123:5: E722 do not use bare except'
```

@chriskuehl and I think we've traced it to pre-commit installing flake8 unpinned on its first attempt, and not updating it later.

Is that enough to work with, or should I try to find more concrete repro steps?

**Comment by asottile** [comment]
Indeed it [does not](https://github.com/pre-commit/pre-commit-hooks/blob/e718847ccbc65cd72a89fefb4db61c55ec4d430d/setup.py#L28)

If you'd like to pin it, I'd suggest using [`additional_dependencies`](http://pre-commit.com/#pre-commit-configyaml---hooks) to do so.

Alternatively, define a local hook with a pinned version:

```yaml
# untested
-   repo: local
    hooks:
    -   id: flake8
        name: flake8
        language: python
        entry: flake8
        types: [python]
        additional_dependencies: [flake8==...]
```
