### ISSUE TITLE
How do I configure arguments for a given hook?

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [pre-commit/pre-commit-hooks#262]
Apologies if the question looks too simple. I'm new to pre-commit. 

I followed these steps to set things up:
```
brew install pre-commit
cd my_repo
pre-commit install
```
and then created a `.pre-commit-config.yaml` file inside `my_repo` with the following contents:

```
-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: v1.2.0  # Use the ref you want to point at
    hooks:
    -   id: check-added-large-files
```

My understanding is that `check-added-large-files` supports arguments `args: ['--maxkb=123']`. 

I would like to set up the hook so that it prevents me from committing files larger than 50MB *any time* I try to git commit anything on the repo. Where exactly do I specify these arguments?

**Comment by asottile** [comment]
You'll add those args to the hook dictionar itself -- it'll look something like this:

```yaml
-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: v1.2.0  # Use the ref you want to point at
    hooks:
    -   id: check-added-large-files
        args: [--maxkb=123]
```

The full docs for this can be found here: [Passing arguments to hooks](https://pre-commit.com/#passing-arguments-to-hooks)

**Comment by amelio-vazquez-reina** [comment]
Thanks @asottile 👍 Easier than I thought!

**Comment by asottile** [comment]
Awesome!  Thanks for the issue :)

**Comment by metmajer** [comment]
@asottile: is there any chance to pass a quoted string argument to a given hook? Use-case here is that I want my own hook to accept a JSON object for string replacements. When I commit the pre-commit config to `git`, I get the following error:

```
- repo: git://github.com/getcloudnative/pre-commit-hooks
  rev: v1.0.0
  hooks:
  - id: jenkins_pipeline_from_terraform_input_vars
    args: [--replacements='{ "params.name.toString()": "convertToName(params.name.toString())" }']
```


```
An error has occurred: InvalidConfigError:
==> File /Users/metmajer/Workspace/pre-commit-hooks/.pre-commit-config.yaml
=====> while scanning a quoted scalar
  in "<unicode string>", line 34, column 97:
     ... oName(params.name.toString())" }']
                                         ^
found unexpected end of stream
  in "<unicode string>", line 46, column 1:

    ^
```

Thanks for sharing further insights!
