### ISSUE TITLE
Add pytest hook

### ISSUE THREAD

**Issue by dspechnikov** [pre-commit/pre-commit-hooks#291]
I was surprised `pytest` hook is missing. Is there any reason not to have it? 

`pytest` is popular so I think we should include. If that's okay, I'll start working on PR.

**Comment by dspechnikov** [comment]
Now that I'm tried to implement it, I guess I understand the reason. Is it because `pre-commit` can't use existing project environment and there is no way to install project dependencies other than copying them to `additional_dependencies`?

**Comment by asottile** [comment]
The main reasons:

1. tests are often slow, committing should be _fast_
2. It would have to be a system / script hook since you'd need _repository specific_ dependencies installed (as you've noticed)

That said, if you wanted to do something like this, I've outlined a way to do that [here](https://github.com/pre-commit/pre-commit/issues/761#issuecomment-394167542)

Also a fun bit of history, the _original_ `pre-commit` used to run [`make test` as a hook](https://github.com/pre-commit/pre-commit/blob/7bb7f4a4838dbd5d52873187cc9b1b51b83cf0ba/pre-commit.py#L82-L86) but was quickly removed due to (1.) above.

**Comment by jgstew** [comment]
You can do this like this:

```
  - repo: https://github.com/christophmeissner/pytest-pre-commit
    rev: 1.0.0
    hooks:
      - id: pytest
        pass_filenames: false
        always_run: true
        stages: [manual]
        additional_dependencies:
          - requests
```

The issue is all dependencies must be enumerated by additional_dependencies, which is not a great option for a very complicated project.

The advantage of this approach is it is more portable.

The `stages: [manual]` or similar setting can help by not having it run on EVERY commit, but rather run only when requested. Could also use a pre-push stage or similar to still run, just not as often as every commit for speed reasons.

You can run the manual stage when you want like this:

`pre-commit run --hook-stage manual`

You can then have all pre-commit hooks including this one run in a github action context like this:

```
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: >-
            --color=always
            --from-ref ${{ github.event.pull_request.base.sha || github.event.before }}
            --to-ref ${{ github.event.pull_request.head.sha || github.sha }}
            --hook-stage manual
```
