### ISSUE TITLE
mixed-line-ending hook doesn't list failures when --fix=no

### ISSUE THREAD

**Issue by gimbo** [pre-commit/pre-commit-hooks#340]
It would be useful if the mixed-line-ending hook actually listed failed files when `--fix=no`, rather than just saying "Failed". As it stands, it's pretty useless in that mode except when run vs a single file!

E.g. this config:

```
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.0.0  # Use the ref you want to point at
    - id: mixed-line-ending
      args:
        - --fix=no
```

If I run it against a change containing a mixed line ending, I get simply:

```
$ pre-commit run -v
[mixed-line-ending] Mixed line ending....................................Failed
```

I might have chance to look at this and fix it, but opening this is as a placeholder and in case anyone else gets to it first.
