### ISSUE TITLE
Howto setup file-contents-sorter

### ISSUE THREAD

**Issue by xasx** [pre-commit/pre-commit-hooks#357]
You maybe aware of the encryption tool [StackExchange/blackbox][1]

It tracks the encrypted files in `keyrings/live/blackbox-files.txt`. This file soon-ish gets a merge mess up when worked on collaboratively because the tool sorts it when adding new files. Therefore, I wanted to make use of `file-contents-sorter`.

However, I am a bit stuck with configuring it properly. I tried many combinations. The union of all and what I consider most reasonable is

```yaml
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
       - id: file-contents-sorter
         verbose: true
         files: 'blackbox\-files\.txt$'
         args: ['./keyrings/live/blackbox-files.txt']
```

Can you please direct me to the right solution here? Thanks. :heart_decoration: 

[1]: https://github.com/StackExchange/blackbox
