### ISSUE TITLE
Document usage via repo local method

### ISSUE THREAD

**Issue by ssbarnea** [pre-commit/pre-commit-hooks#406]
While I recently learn how to use flake8 hook without having to configure another git repository, I was not able to identify how to use these hooks from this repository in the same way. This needs to be documented and included at the bottom of the README file, near the pip  install method.

After some investigation I was able to find a way to call these hooks bug the approach does not scale for multiple hooks, being totally impractical:
```
repos:
  - repo: local
    hooks:
      - id: trailing-whitespace
        name: trailing-whitespace-fixer
        entry: trailing-whitespace-fixer
        language: python
        additional_dependencies:
          - pre-commit-hooks
```
