### ISSUE TITLE
Why is `sort-simple-yaml` hook skipped?

### ISSUE THREAD

**Issue by estensen** [pre-commit/pre-commit-hooks#416]
I want to sort a yaml file. I found `sort-simple-yaml`, but it always skips my yaml files.
I use pre-commit version 1.18.3

.pre-commit-config.yaml
```
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: sort-simple-yaml
```

list.yaml
```
b: 1
d: 2
c: 2
a: 1
```

Commiting a simple yaml file and the sorting is skipped:
```
$ git add -A
$ git commit -m "Add list"
Sort simple YAML files...............................(no files to check)Skipped
```

Even running it on all files the hook is skipped:
```
$ pre-commit run -a
Sort simple YAML files...............................(no files to check)Skipped
```

**Comment by asottile** [comment]
I'm adding a little blurb about this in the docs in #417

**Comment by estensen** [comment]
Adding a broad regex the file is found, but no sorting is happening.
If an empty line is added to the end it will be removed by the hook.

```
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: sort-simple-yaml
        files: \.yaml$
```

A file only containing keys won't be sorted either:

list.yaml
```
b
d
c
a
```
