### ISSUE TITLE
Best hook to check yaml and helm charts

### ISSUE THREAD

**Issue by jeunii** [pre-commit/pre-commit-hooks#420]
I currently have a repo that has both standard yaml files and has helm charts in it. So I want pre-hook to check both kinds of files. My `.pre-commit-config.yaml` states
```
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: check-yaml
    args: [--allow-multiple-documents]
- repo: https://github.com/gruntwork-io/pre-commit
  rev: v0.0.9
  hooks:
  - id: helmlint
```
When I run the 2 hooks on my repo, I always get an error
```
Check Yaml...............................................................Failed
hookid: check-yaml

while constructing a mapping
  in "charts/base/templates/rbac/team/role-binding.yaml", line 1, column 1
found unhashable key
  in "charts/base/templates/rbac/team/role-binding.yaml", line 1, column 2
while constructing a mapping
  in "charts/base/templates/rbac/cluster-admin.yaml", line 1, column 1
found unhashable key
  in "charts/base/templates/rbac/cluster-admin.yaml", line 1, column 2

helmlint.................................................................Passed
```

And the 2 files are the ones that are supposed to be templated by helm.

So is there a work around to this ? Or a better yaml check hook that I can use that doesnt freak out as soon as it scans a helm template file ?
