### ISSUE TITLE
Support glob pattern in detect-private-key hook

### ISSUE THREAD

**Issue by mcyprian** [pre-commit/pre-commit-hooks#427]
The `detect-private-key` hook currently has filenames argument, but it seems it doesn't support glob patterns. In a bigger project, you sometimes want to exclude test directory from the check. It would be very useful if there is an option to do something like
```
hooks:
    ...
    - id: detect-private-key
        args: [src/*] 
```
