### ISSUE TITLE
Feature: TODO, FIXME, HACK hook

### ISSUE THREAD

**Issue by daniel-wtd** [pre-commit/pre-commit-hooks#439]
Hi,

thank you so much for this cool tool and all the nice hooks.

Is it possible to add a hook, which checks for TODO, FIXME, HACK comments/texts in files?

**Comment by asottile** [comment]
The [`pygrep`](https://pre-commit.com/#pygrep) language works particularly well for this -- for example:

```yaml
-   repo: local
    hooks:
    -   id: prevent-hax
        name: prevent hax
        entry: '# *HAX\b'
        language: pygrep
        files: [text]
```
