### ISSUE TITLE
Understanding how to run commit-msg hook

### ISSUE THREAD

**Issue by cristian05** [pre-commit/pre-commit-hooks#498]
I'm trying to run a **node script to validate my commit message**, this script has a npm dependecy that is [chalk](https://github.com/chalk/chalk). The script is on my local machine and works well with [husky](https://github.com/typicode/husky) and `package.json`, but I can't get it to work with `pre-commit`. 

### I run:
`pre-commit install --hook-type commit-msg`
`git add -A`
`git commit -m "my message`

This passed but my commit is not valid, because im using [Angular commit message convention](https://gist.github.com/stephenparish/9941e89d80e2bc58a153#format-of-the-commit-message). 

### The output
```
Installing environment for local.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
Validate Commit Message..................................................Passed
````

Im doing something wrong in my configuration?

### .pre-commit-config.yaml
```
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: validate-commit-message
        name: Validate Commit Message
        language: node
        language_version: 14.4.0
        entry: node scripts/git/commit-message.js
        additional_dependencies: ['chalk']
        stages:
          - commit-msg
```
