### ISSUE TITLE
no-commit-to-branch does not respect excludes

### ISSUE THREAD

**Issue by marcjay** [pre-commit/pre-commit-hooks#500]
**Reproduction steps**
.pre-commit-config.yaml:
```
repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: 'v3.1.0'
    hooks:
      - id: 'no-commit-to-branch'
        args: ['--branch', 'master']
        exclude: 'foo.txt'
```
git status:
```
$ git status
On branch master

No commits yet

Changes to be committed:
  (use "git rm --cached <file>..." to unstage)
	new file:   foo.txt
```
Output:
```
 $ pre-commit run
Don't commit to branch...................................................Failed
- hook id: no-commit-to-branch
- exit code: 1
```

Appreciate this might be somewhere between a bug and a feature request. The particular use-case I'm trying to address concerns a repo with a structure of:
```
.
├── application-code
│   └── code-which-must-be-peer-reviewed
└── integration-test-code
    └── test-code-which-can-go-straight-to-master
```
So I was expecting the following to work:
```
  - id: 'no-commit-to-branch'
    args: ['--branch', 'master']
    exclude: '^integration-test-code/'
```
This also applies to `exclude_types`. I believe the fix would be just to revert https://github.com/pre-commit/pre-commit-hooks/commit/66eb9d3aec1237b5aae3785b22da6b2f699b5d54 (EDIT: and drop the `always_run`) but I'm sure there was a good reason for that change, so wanted to check that before raising a PR. Many thanks!
