### ISSUE TITLE
[feature request] print checker

### ISSUE THREAD

**Issue by henryiii** [pre-commit/pre-commit-hooks#510]
Twice now I've make a release with a debugging print statement in my code! I'd like to be able to add a check for print calls inside a specific subdirectory. My imaged use:

```yaml
- id: check-for-functions
  files: src
  args:
    - print
```

It would look for `\bprint\b`. It would basically be almost identical to the debug-statements checker, I expect, just configurable. Thoughts?

PS: I see that the debug statement checker is smarter than that, and uses the ast. This could either be hardcoded to print then, or maybe you could put arbitrary functions to ignore?

**Comment by asottile** [comment]
This repo is mostly moving towards language agnostic hooks and so we probably wouldn't accept a new python-specific hook.  Also `print` isn't inherently bad so I'm not sure it makes sense to write a new hook for it

You might find `flake8-print` helpful instead, it's easy to add plugins to flake8 by using [`additional_dependencies`](https://pre-commit.com/#config-additional_dependencies)

alternatively, if you want a quick-and-dirty hook, you could set up a local [`pygrep`](https://pre-commit.com/#pygrep) hook something like this:

```yaml
-   repo: local
    hooks:
    -   id: no-print
        name: no print() function
        entry: \bprint\b
        language: pygrep
        types: [python]
```

**Comment by henryiii** [comment]
Thanks! This worked for me:

```yaml
- repo: https://github.com/pycqa/flake8
  rev: 3.8.3
  hooks:
  - id: flake8
    exclude: docs/conf.py
    additional_dependencies: [flake8-bugbear]
  - id: flake8
    name: Print check
    files: src
    additional_dependencies: [flake8-print]
    args:
      - --select
      - T
```

(I don't know how to restrict a check to a directory in flake8 except by splitting it in pre-commit as above)

A general regex hook that would error if matches were found would still be useful and general, IMO.
