### ISSUE TITLE
check-yaml doesn't allow for multiple `<<` in docker-compose as keys

### ISSUE THREAD

**Issue by alecgerona** [pre-commit/pre-commit-hooks#527]
check-yaml hook flags having more than one `<<` in docker-composes as a duplicate key.

**Comment by asottile** [comment]
show example and config

**Comment by alecgerona** [comment]
```yml
x-some-config: &some-config
    SOME_SETTING: SETTING
x-another-config: &another-config
    SOME_SETTING: SETTING2
...
  api:
    restart: always
    image: image
    container_name: container
    environment:
      <<: *some-config
      <<: *another-config
```
