### ISSUE TITLE
False positives raised by `check-executables-have-shebangs` in VS Code Dev Containers

### ISSUE THREAD

**Issue by lsorber** [pre-commit/pre-commit-hooks#528]
When developing within a container using VS Code's [Dev Containers](https://code.visualstudio.com/docs/remote/containers) feature, the `check-executables-have-shebangs` raises false positives for staged files, see log below. When switching back to local development, the same check passes without issue.

```
Check that executables have shebangs.....................................Failed
- hook id: check-executables-have-shebangs
- exit code: 1

.devcontainer/devcontainer.json: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x .devcontainer/devcontainer.json`
  If it is supposed to be executable, double-check its shebang.
.cruft.json: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x .cruft.json`
  If it is supposed to be executable, double-check its shebang.
.vscode/settings.json: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x .vscode/settings.json`
  If it is supposed to be executable, double-check its shebang.
environment.run.yml: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x environment.run.yml`
  If it is supposed to be executable, double-check its shebang.
```

**Comment by asottile** [comment]
please show your config, this was changed recently and you  may not be on the latest version

otherwise this may be a duplicate of #512? I'm not sure

I assume you're on windows?

**Comment by asottile** [comment]
but, if vs code spaces is adding `+x` to every file, that's a problem with code spaces and not this tool

**Comment by lsorber** [comment]
I'm on macOS, and pre-commit 3.2.0 produced the logs above. I checked the executable flag on each file and none of them were executable according to `ls`.

**Comment by asottile** [comment]
what happens if you use `os.access(file, os.X_OK)` on the particular file? that's how pre-commit determines if the file is executable or not

**Comment by lsorber** [comment]
With pre-commit 3.3.0:
![image](https://user-images.githubusercontent.com/4543654/98912524-834e3f80-24c6-11eb-8616-2fadd6dd9667.png)

**Comment by asottile** [comment]
you still haven't shown your configuration, there's no such version 3.3.0 of pre-commit (and the pre-commit version isn't relevant here)

do you know what operating system the remote "container" is running on?  can you run this: https://github.com/asottile/scratch/wiki/platforms

**Comment by lsorber** [comment]
I meant 3.3.0 of the pre-commit hooks.

Here's my `.pre-commit-config.yaml`, nothing special:
```
# https://pre-commit.com
default_stages: [commit, manual]
fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-builtin-literals
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: detect-private-key
      - id: mixed-line-ending
      - id: trailing-whitespace
        types: [python]
      - id: end-of-file-fixer
        types: [python]
```

Here's the output of that script:
```
- **`sys.version`**: `'3.8.6 | packaged by conda-forge | (default, Oct  7 2020, 19:08:05) \n[GCC 7.5.0]'`
- **`os.name`**: `'posix'`
- **`sys.platform`**: `'linux'`
- **`platform.system()`**: `'Linux'`
- **`platform.python_implementation()`**: `'CPython'`
- **`sys.implementation.name`**: `'cpython'`
- **`sysconfig.get_platform()`**: `'linux-x86_64'`
```
