### ISSUE TITLE
arg exclude to trailing-whitespace

### ISSUE THREAD

**Issue by lucasrcezimbra** [pre-commit/pre-commit-hooks#539]
It would be great to have an `exclude` argument in `trailing-whitespace` receiving files for which the hook should not be executed.

If it make sense I can work on it and open a PR.

Does this make sense for the project?

**Comment by asottile** [comment]
you're missing one of the main points of pre-commit, but you're not alone -- check these duplicates:  #536 #535 #517 #496 #391

**Comment by lucasrcezimbra** [comment]
Oh, sorry. I search "exclude trailing-whitespace" and didn't see the issues of other hooks. 

It works. Thanks!

**Comment by levsa** [comment]
I tried the global exclude option but it didn't work for `trailing-whitespace`. It worked when adding and exclide to the `trailing-whitespace` section though.

**Comment by asottile** [comment]
@levsa show your config

**Comment by levsa** [comment]
> @levsa show your config

This works:

```
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.1.0
  hooks:
  - id: trailing-whitespace
    exclude: 3rd_party
  - id: check-yaml
    entry: check-yaml --unsafe
  - id: end-of-file-fixer
  - id: check-merge-conflict
  - id: check-symlinks
  - id: no-commit-to-branch
    args: [--branch, main]
```

but not this:

```
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.1.0
  exclude: 3rd_party
  hooks:
  - id: trailing-whitespace
  - id: check-yaml
    entry: check-yaml --unsafe
  - id: end-of-file-fixer
  - id: check-merge-conflict
  - id: check-symlinks
  - id: no-commit-to-branch
    args: [--branch, main]
```

I've tried different patterns.
