### ISSUE TITLE
YAML check fails for double exclamation marks

### ISSUE THREAD

**Issue by chbndrhnns** [pre-commit/pre-commit-hooks#552]
In [mkdocs](https://www.mkdocs.org/), the following configuration is valid, however, the pre-commit check fails.

The error:

```
Check Yaml...............................................................Failed
- hook id: check-yaml
- exit code: 1

could not determine a constructor for the tag 'tag:yaml.org,2002:python/name:materialx.emoji.twemoji'
  in "mkdocs.yml", line 29, column 20
```

```yaml
site_name: p
site_description: API documentation
site_url: http://x/y/z
repo_url: http://x/y/z
edit_uri: tree/master/docs/
docs_dir: docs/

theme:
  name: "material"
  palette:
    accent: "amber"

extra_css:
  - css/docstring.css

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - Introduction: 'index.md'
```
