### ISSUE TITLE
check-yaml hook failed with "!!"

### ISSUE THREAD

**Issue by zillionare** [pre-commit/pre-commit-hooks#567]
I have the following yaml (it's mkdocs.yml):
```
markdown_extensions:
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
  - admonition
  - toc:
      baselevel: 2
      permalink: true
      slugify: !!python/name:pymdownx.slugs.uslugify
```
the config works with mkdocs. However, if I run pre-commit run on this file, it complains:
```
could not determine a constructor for the tag 'tag:yaml.org,2002:python/name:pymdownx.slugs.uslugify'
  in "mkdocs.yml", line 22, column 16
```

the pre-commit-config.yml
```
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-merge-conflict
    - id: check-yaml
```
Please suggest if this is a bug or I'm using it in incorrect way. Thanks!
