### ISSUE TITLE
check-yaml and cloud-config

### ISSUE THREAD

**Issue by ausfestivus** [pre-commit/pre-commit-hooks#577]
I have the following cloud-config snippet:

```yaml
write_files:
%{ if role == "primary" }
- path: /var/lib/cloud/scripts/per-once/install-app.sh
  owner: root:root
  permissions: "0555"
  encoding: b64
  content: ${install_app_sh}
%{ endif ~ }
```

When I do a `pre-commit run -a` with the `check-yaml` hook:
```yaml
- repo: git://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
    - id: check-yaml
```

`pre-commit` is failing with:

```
Check Yaml...............................................................Failed
- hook id: check-yaml
- exit code: 1

while scanning a directive
  in "modules/configs/templates/cloud-init/cloud-config.yaml", line 44, column 1
could not find expected directive name
  in "modules/configs/templates/cloud-init/cloud-config.yaml", line 44, column 2
```

Ive not been able to really track down anything that can help me isolate the problem

I have another repo with similar yaml which DOES pass the `pre-commit` checks.
```yaml
runcmd:
  %{ if environment == "non-prod" }
  - echo "Running letsencrypt in dev mode."
  # This certbot command will retrieve a staging cert that is not trusted by clients.
  # When we are testing this and may trigger the LE rate limits it should be used.
  - 'certbot -n -d ${hostname}.${domain} --email $EMAIL --apache --agree-tos --redirect --hsts --staging'
  %{ endif }
```

Im pretty sure i've got all the YAML double-spaced and not tabbed. I just cant get to the bottom of why it works in one repo and not another.

**Comment by asottile** [comment]
the hook is correct, that is very much **not** yaml but some template language

show your full configuration from both repositories and their exact filenames

**Comment by ausfestivus** [comment]
Both files are templates which create a cloud-config.yaml file. The templates are used by the Terraform `templatefile` function to produce a valid cloud-init config for a VM to run when it boots.

Working template:         https://gist.github.com/ausfestivus/d0eb76ca1eb3eb9b21b20f434ad775cb
Not working template:  https://gist.github.com/ausfestivus/c36efe87f26795115b6d5aff61ff80f2

The terraform `templatefile` function: https://www.terraform.io/docs/language/functions/templatefile.html

**Comment by asottile** [comment]
yeah both of those trip `check-yaml` -- show your **pre-commit** config

**Comment by ausfestivus** [comment]
```yaml
repos:
- repo: git://github.com/antonbabenko/pre-commit-terraform
  rev: v1.48.0
  hooks:
    - id: terraform_fmt
    - id: terraform_validate
    - id: terraform_docs
    - id: terraform_tfsec
- repo: git://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
    #- id: check-yaml # disabled atm due to https://github.com/pre-commit/pre-commit-hooks/issues/577
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: check-case-conflict
    - id: check-merge-conflict
    - id: check-executables-have-shebangs
    - id: detect-aws-credentials
    - id: detect-private-key
- repo: git://github.com/jumanjihouse/pre-commit-hooks
  rev: 2.1.5
  hooks:
    - id: shfmt
      args: ['-l', '-i', '2', '-ci', '-sr', '-w']
```

**Comment by asottile** [comment]
can you show both of your configurations?

**Comment by ausfestivus** [comment]
Sorry, I should try and be more comprehensive with the info being provided. Im juggling a few different issues at the moment.

```yaml
repos:
- repo: git://github.com/antonbabenko/pre-commit-terraform
  rev: v1.45.0
  hooks:
    - id: terraform_fmt
    - id: terraform_validate
    - id: terraform_docs
    - id: terraform_tfsec
- repo: git://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: check-case-conflict
    - id: check-merge-conflict
```

My previous statement that check-yaml worked in one repo and not the other was incorrect. I realised that the `-id: check-yaml` line item was commented out in the working repo.

The problem is occurring in both my repos.
