### ISSUE TITLE
`pretty-format-json` uses system's default line separator when formatting

### ISSUE THREAD

**Issue by jack1142** [pre-commit/pre-commit-hooks#622]
## Description

Running `pretty-format-json` on incorrectly formatted JSON but with correct line endings will cause to reformat JSON *and* change the line endings to whatever is the default line separator on the OS you're currently using.

## Example
`.pre-commit-config.yaml`:
```yaml
default_language_version:
  python: python3.8
repos
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: mixed-line-ending
        args:
          - "--fix=lf"
      - id: pretty-format-json
        args:
          - "--autofix"
          - "--indent=4"
          - "--no-sort-keys"
```
`some_json_file.json` (using LF endings):
```json
{
  "bad": "indentation"
}
```
## Result
```
D:\test_repository> git add test_file.json

D:\test_repository> pre-commit run
Mixed line ending........................................................Passed
Pretty format JSON.......................................................Failed
- hook id: pretty-format-json
- exit code: 1
- files were modified by this hook

Fixing file test_file.json

D:\test_repository> git add test_file.json
warning: CRLF will be replaced by LF in test_file.json.
The file will have its original line endings in your working directory

D:\test_repository> pre-commit run
Mixed line ending........................................................Failed
- hook id: mixed-line-ending
- exit code: 1

test_file.json: fixed mixed line endings

Pretty format JSON.......................................................Passed
```

## Workaround
Reordering the checks can be used to work around this issue as that achieves proper full reformat on the first try with both of the checks failing.

## Proposed solution
Detection of the type of line endings already in the file *or* an option to set different line endings in the `pretty-format-json`.
