### ISSUE TITLE
Unexpected ':'

### ISSUE THREAD

**Issue by tdegeus** [pre-commit/pre-commit-hooks#650]
I have the following bit in `.pre-commit-config.yaml`
```yaml
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: debug-statements
- repo: https://github.com/PyCQA/flake8
  rev: 3.9.2
  hooks:
  - id: flake8
    args: [--max-line-length=100, --per-file-ignores=python/myrepo/*.py:F401]
```
However, I'm getting a persistent 
```
while scanning a plain scalar
  in ".pre-commit-config.yaml", line 13, column 35
found unexpected ':'
  in ".pre-commit-config.yaml", line 13, column 73
```

The syntax that I use in legal, and I think the only syntax. How do I get rid of this error?

**Comment by asottile** [comment]
the syntax you use is not legal, quote it

```yaml
    args: [--max-line-length=100, '--per-file-ignores=python/myrepo/*.py:F401']
```

**Comment by tdegeus** [comment]
Thanks @asottile 

I fact the line was a result of formatting with 
```yaml
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.1.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']
```
so it seems that the two interfere
