### ISSUE TITLE
Add ansible-vault encryption check to hooks

### ISSUE THREAD

**Issue by nicpayne713** [pre-commit/pre-commit-hooks#651]
It would be awesome if something like this https://git.iamthefij.com/iamthefij/ansible-pre-commit was available within this repo. We are starting to use ansible-vault and already use pre-commit, but it would be a challenge for my team to have to setup a custom hook on each individual PC. If we could just add an id to our config for this it would be super easy to ensure our credentials files remain secure.

**Comment by asottile** [comment]
this repository (pre-commit/pre-commit-hooks) is meant for language-agnostic generic hooks.  something specific like that would not be accepted here

you should be able to use that repository directly though or write one of your own which does the same thing

I think you'd do something like this:

```yaml
-   repo: https://git.iamthefij.com/iamthefij/ansible-pre-commit
    rev: ...  # fill this out with whatever tag / sha you want
    hooks:
    -   id: encryption-check
```

you can probably also replace that entire repo with a [`pygrep` hook](https://pre-commit.com/#pygrep) which looks for the [marker](https://git.iamthefij.com/iamthefij/ansible-pre-commit/src/branch/master/encryption-check.sh#L7)
