### ISSUE TITLE
how to pass list of files to file-content-sorter?

### ISSUE THREAD

**Issue by nbraun-wolf** [pre-commit/pre-commit-hooks#663]
Hi, I am interested in sorting some files, but I don't get it working. I couldn't find proper [documentation](https://github.com/pre-commit/pre-commit-hooks#file-contents-sorter) on this hook, and even after reading the source code and tests, I couldn't figure out how to pass the files.

The [flags](https://github.com/pre-commit/pre-commit-hooks/blob/master/pre_commit_hooks/file_contents_sorter.py#L61) are also not documented.

Trying something like this.

```yaml
- id: file-contents-sorter
  args: [gitignore, --unique]
```

**Comment by nbraun-wolf** [comment]
O figured it out, it will be still nice to documents this and also the flags.

```yaml
 - id: file-contents-sorter
   files: .gitignore|.dockerignore
   args: [--unique]
```
