### ISSUE TITLE
issue with check-yaml and .gitlab-ci.yml

### ISSUE THREAD

**Issue by stefreak** [pre-commit/pre-commit-hooks#681]
First of all, thank you for the excellent work.

I started using check-yaml, and when I tried to use "map merging" as described in the gitlab documentation (https://docs.gitlab.com/ee/ci/yaml/yaml_specific_features.html) I noticed that check-yaml complains about duplicate keys:

```
Check Yaml...............................................................Failed
- hook id: check-yaml
- exit code: 1

while constructing a mapping
  in ".gitlab-ci.yml", line 39, column 3
found duplicate key "<<"
  in ".gitlab-ci.yml", line 40, column 3

To suppress this check see:
   http://yaml.readthedocs.io/en/latest/api.html#duplicate-keys
```

Code example triggering this:
```
.secure-runner: &secure-runner
  tags:
    # This runner is more secure, but it is slower.
    - onetime

.docker-build: &docker-build
  image: docker:20.10.10
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGE_TAG -f $DOCKERFILE .
    - docker push $IMAGE_TAG

Build production container:
  <<: *secure-runner
  <<: *docker-build
  stage: prod-build
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    DOCKERFILE: Dockerfile
```

I can work around this by using `--unsafe`, but I believe I do not need the multi-document syntax. Is it also possible to allow more fine grained control over which yaml features are allowed, and which aren't?
