### ISSUE TITLE
name-tests-test hook does not detect the files in tests

### ISSUE THREAD

**Issue by 4ndt3s** [pre-commit/pre-commit-hooks#693]
I have the same problem detected in issue #664. Basically, this hook does not detect any file inside the tests folder. 

The configuration file:

```
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: name-tests-test

```
The folder structure:
```
...
├── tests
│   ├── add_test.py
│   ├── app_test.py
│   ├── conftest.py
│   └── health_test.py
...
```
The error:
```
Tests should end in _test.py.........................(no files to check)Skipped
```
Any suggestion? Thanks in advance.
