### ISSUE TITLE
A hook that can run an arbitrary command

### ISSUE THREAD

**Issue by colindean** [pre-commit/pre-commit-hooks#699]
I'm adopting pre-commit in my projects, many of which already have significant automation behind a `make check` Make task. CI runs this task and some devs remember to run it manually. In comes pre-commit to automate _all_ of them running it!

I'd really like to be able to run this as a part of my pre-commit config, but I can't seem to find a plugin that allows me to run basically any command. Ideally, this would run in the same directory as the `.pre-commit-config.yaml` file.

I'd imagine its configuration would look something like this:

```yaml
repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      hooks:
        - id: run-command-in-repo
          args: make check
```

This should be simple enough to implement myself but it seems strange that this isn't already a thing given my perception of its simplicity and being a fallback to avoid having to setup a plugin+repo for it. Maybe something like this already exists and I can't find it. Nothing jumped out in the [plugin/repo list](https://pre-commit.com/hooks.html).
