### ISSUE TITLE
forbid-new-submodules marked not applicable on repo w/o submodules

### ISSUE THREAD

**Issue by ChiefGokhlayeh** [pre-commit/pre-commit-hooks#707]
This might be intended behavior, but I'd like to get confirmation.

Since [`4.1.0`](https://github.com/pre-commit/pre-commit-hooks/tree/v4.1.0), meta-hook `check-hooks-apply` marks `forbid-new-submodules` as _"does not apply"_, if the repo does not contain any submodules.

The hook `forbid-new-submodules` itself correctly warns when adding submodules to a previously empty repo, so it technically **does** apply.

This might have to do with the changes introduced in #619.

Steps to reproduce:

1) Create new repo
    ```console
    $ git init issue-707 && cd issue-707
    ```
2) Create `.pre-commit-config.yaml` with following content:
    ```yaml
    repos:
      - repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v4.1.0
        hooks:
          - id: forbid-new-submodules
      - repo: meta
        hooks:
          - id: check-hooks-apply
    ```
3) Commit `.pre-commit-config.yaml`
    ```console
    $ git add .pre-commit-config.yaml && git commit -m "Add pre-commit config"
    ```
4) Run the following:
    ```console
    $ pre-commit run --all
    forbid new submodules................................(no files to check)Skipped
    Check hooks apply to the repository......................................Failed
    - hook id: check-hooks-apply
    - exit code: 1

    forbid-new-submodules does not apply to this repository
    ```
5) Add submodule and force-commit
    ```console
    $ git submodule add https://github.com/pre-commit/pre-commit-hooks.git
    $ git commit -m "Add some submodule" -n
    ```
6) Run the following:
    ```console
    $ pre-commit run --all
    forbid new submodules....................................................Passed
    Check hooks apply to the repository......................................Passed
    ```

**Comment by asottile** [comment]
indeed this is a bit of a tricky case -- admittedly the original `forbid-new-submodules` was designed for a migration where submodules were slowly removed over time (and wasn't necessary afterwards)

#619 changed how the hook matches files which causes it to no longer match on a repo without submodules

**Comment by ChiefGokhlayeh** [comment]
I admit, the chances of someone _accidentally_ adding a submodule are very slim. I simply added it to all my configs as a _nice to have_.

If this is a "won't fix", feel free to close the issue. I can simply remove the hook where no longer applicable.

**Comment by asottile** [comment]
you can _maybe_ restore the old behaviour by overriding `types: []` but then it probably does more work than it needs to

**Comment by asottile** [comment]
I think the resolution of this is "use this while migrating away from submodules" and once you're done you can replace it with a simple `language: fail` hook:

```yaml
-   repo: local
    hooks:
    -   id: no-submodules
        name: no submodules
        language: fail
        entry: submodules are not allowed in this repository
        types: [directory]
```
