### ISSUE TITLE
Proposal: add check for permitted characters in pathnames

### ISSUE THREAD

**Issue by noahp** [pre-commit/pre-commit-hooks#736]
See #734 .

Check each pathname for permitted characters. Proposed default is alphanumeric plus `-_.`.

Include arguments for explicitly specifying the allowlist and extending the default.

Would a regex strategy be preferable for greater control over position of characters?

**Comment by asottile** [comment]
this can be done easily (with full control over the pattern) directly without needing any special code:

```yaml
-   repo: local
    hooks:
    -   id: check-alphanumeric-filenames
        name: filenames must be alphanumeric
        language: fail
        entry: 'filenames must be alphanumeric:'
        exclude: '^[a-zA-Z0-9\._-]+$'
```
