### ISSUE TITLE
Flake8 --per-file-ignores critical error in pre-commit

### ISSUE THREAD

**Issue by pseudo-rnd-thoughts** [pre-commit/pre-commit-hooks#757]
Im trying to use flake8 with the parameter `--per-file-ignores`, [docs](https://flake8.pycqa.org/en/latest/user/options.html?highlight=per-file-ignores#cmdoption-flake8-per-file-ignores)

When I run this on its own I have no issues (I only want to ignore import module not used warnings for every `__init__.py`)
`flake8 --per-file-ignores="*/__init__.py:F401"`
However when I run it in pre-commit then I get the following error
```
flake8...................................................................Failed
- hook id: flake8
- exit code: 1

There was a critical error during execution of Flake8:
Expected `per-file-ignores` to be a mapping from file exclude patterns to ignore codes.

Configured `per-file-ignores` setting:

    "*/__init__.py:F401"
```

My setup is 
```
repos:
  - repo: https://gitlab.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        args:
          - --per-file-ignores='*/__init__.py:F401'
          - --max-complexity=30
          - --max-line-length=120
          - --show-source
          - --statistics
```
