### ISSUE TITLE
Long lines hook

### ISSUE THREAD

**Issue by tgross35** [pre-commit/pre-commit-hooks#769]
It would be nice to have a hook that just checks for lines over a specified length. This is useful for any sort of manually-wrapped files, and it doesn't seem like any other hooks do it (files with linters being the exception).

**Comment by tgross35** [comment]
Came up with a shell script version that's not too bad.

```yaml
- id: check-long-lines
  name: Check long lines
  language: system
  verbose: true
  entry: bash -c "! grep '.\{80\}' $@"
  exclude_types:
    [python, sql, css, csv, binary, json, yaml]
```

Might still not be a terrible hook to think about adding so I'll leave the issue open for now. Close at will.
