### ISSUE TITLE
end-of-file-fixer corrupts binary files

### ISSUE THREAD

**Issue by johnmcfarlane** [pre-commit/pre-commit-hooks#781]
Binary files typically don't need to end in a newline sequence, so when _end-of-file-fixer_ hook is invoked on a file that is marked as _binary_ (say, in a _.gitattributes_ file), it might be advantageous to avoid adding a newline to that file.

# To reproduce:

_.pre-commit-config.yaml_:

```yaml
---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    hooks:
      - id: end-of-file-fixer
```

_test-data/.gitattributes_:

```
my-binary-file binary
```

_my-binary-file_:

(A binary file that doesn't end in any newline character.)

# Notes

Additionally, the configuration specified by _.gitattributes_ files could help choose the appropriate newline sequence for each text file that is processed.
