### ISSUE TITLE
Files getting flagged as executables without having execution permissions

### ISSUE THREAD

**Issue by 0x326** [pre-commit/pre-commit-hooks#791]
Similar to #762, except it is happening on a normal Windows (non Docker) file system.

```
C:\repos\POM\POM.Customer.Api [produce-event +1 ~4 -0 !]
> git push
[WARNING] Unstaged files detected.
[INFO] Stashing unstaged files to C:\Users\MEYEJOH\.cache\pre-commit\patch1658267097-54504.
dotnet build (startup project)...........................................Passed
dotnet build (unit tests)................................................Passed
dotnet build (AATs)......................................................Passed
dotnet unit tests........................................................Passed
dotnet acceptance tests..................................................Passed
ShellCheck...........................................(no files to check)Skipped
don't commit to branch...................................................Passed
check for merge conflicts................................................Passed
fix utf-8 byte order marker..............................................Passed
trim trailing whitespace.................................................Passed
fix end of files.........................................................Passed
mixed line ending........................................................Passed
check json...........................................(no files to check)Skipped
check toml...........................................(no files to check)Skipped
check xml................................................................Passed
check yaml...........................................(no files to check)Skipped
check that executables have shebangs.....................................Failed
- hook id: check-executables-have-shebangs
- exit code: 1

src/POM.Customer.Api/Program.cs: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x src/POM.Customer.Api/Program.cs`
  If on Windows, you may also need to: `git add --chmod=-x src/POM.Customer.Api/Program.cs`
  If it is supposed to be executable, double-check its shebang.

(as well as 20-30 other files)

check that scripts with shebangs are executable..........................Passed
check for case conflicts.................................................Passed
check for broken symlinks............................(no files to check)Skipped
detect destroyed symlinks................................................Passed
detect private key.......................................................Passed
fix python encoding pragma...........................(no files to check)Skipped
fix requirements.txt.................................(no files to check)Skipped
check vcs permalinks.....................................................Passed
[INFO] Restored changes from C:\Users\MEYEJOH\.cache\pre-commit\patch1658267097-54504.
error: failed to push some refs to 'ssh://github.com/ch-robinson-internal/POM.Customer.Api.git'

C:\repos\POM\POM.Customer.Api [produce-event ≡ +1 ~4 -0 !]
> ls .\src\POM.Customer.Api\Program.cs

    Directory: C:\repos\POM\POM.Customer.Api\src\POM.Customer.Api

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---           7/19/2022  4:44 PM           6433 Program.cs

C:\repos\POM\POM.Customer.Api [produce-event ≡ +1 ~4 -0 !]
> git ls-tree HEAD .\src\POM.Customer.Api\Program.cs
100644 blob ce79723fd9b4279ce66b3566502c0773324c915b    src/POM.Customer.Api/Program.cs

C:\repos\POM\POM.Customer.Api [produce-event ≡ +1 ~4 -0 !]
> cat .\.git\config
[core]
        repositoryformatversion = 0
        filemode = true
        bare = false
        logallrefupdates = true
...
```

```yaml
# pre-commit configuration file (https://pre-commit.com/)
#
# Install Git hooks:
#   pre-commit install -t pre-commit
#   pre-commit install -t pre-push
#   pre-commit install -t post-merge

minimum_pre_commit_version: '2.17'

repos:
  - repo: local
    hooks:
      - id: dotnet-build-src
        name: dotnet build (startup project)
        language: system
        entry: dotnet build src/POM.Customer.Api
        pass_filenames: false
        always_run: true

      - id: dotnet-build-unit-tests
        name: dotnet build (unit tests)
        language: system
        entry: dotnet build tests/POM.Customer.Api.UnitTests
        pass_filenames: false
        always_run: true

      - id: dotnet-build-aat-tests
        name: dotnet build (AATs)
        language: system
        entry: dotnet build tests/POM.Customer.Api.AcceptanceTests
        pass_filenames: false
        always_run: true

      - id: dotnet-unit-tests
        name: dotnet unit tests
        language: system
        entry: dotnet test tests/POM.Customer.Api.UnitTests
        pass_filenames: false
        always_run: true
        stages:
          - push

      - id: dotnet-aat-tests
        name: dotnet acceptance tests
        language: system
        entry: pwsh ./.hooks/run-aats.ps1
        pass_filenames: false
        always_run: true
        stages:
          - push

      # Install ShellCheck with:
      #   scoop install shellcheck
      # See also https://github.com/koalaman/shellcheck#installing
      - id: shellcheck
        name: ShellCheck
        language: system
        entry: shellcheck -x
        types:
          - shell

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      # Workflow
      - id: no-commit-to-branch
        args:
          - -b development
          - -b master
      - id: check-merge-conflict

      # File content
      - id: fix-byte-order-marker
        exclude: '\.\w*proj$|/packages.config$|\.Designer.vb$|\.Designer.cs$|/Web.config$|/app.config$|/Resources.resx$|/?My Project/'

      - id: trailing-whitespace
        exclude: '\.md$|\.markdown$|\.\w*proj$|/packages.config$|\.Designer.vb$|\.Designer.cs$|/Web.config$|/app.config$|/Resources.resx$|/?My Project/'

      - id: end-of-file-fixer
        exclude: '\.\w*proj$|/packages.config$|\.Designer.vb$|\.Designer.cs$|/Web.config$|/app.config$|/Resources.resx$|/?My Project/'

      - id: mixed-line-ending

      # File format
      # - id: pretty-format-json
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable

      # File tree & metedata
      - id: check-case-conflict
      - id: check-symlinks
      - id: destroyed-symlinks

      # Security
      # - id: detect-aws-credentials
      - id: detect-private-key

      # Python
      - id: fix-encoding-pragma
      - id: requirements-txt-fixer

      # Misc
      - id: check-vcs-permalinks

default_language_version:
  python: python3

```
