### ISSUE TITLE
forbid-submodules hook fails

### ISSUE THREAD

**Issue by desecho** [pre-commit/pre-commit-hooks#835]
forbid-submodules hook fails with this error:

```
[ERROR] `forbid-submodules` is not present in repository https://github.com/pre-commit/pre-commit-hooks.  Typo? Perhaps it is introduced in a newer version?  Often `pre-commit autoupdate` fixes this.
```

Config:
```
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: forbid-submodules
```
