### ISSUE TITLE
`check-merge-conflict` hook does not catch a merge conflict

### ISSUE THREAD

**Issue by Alexander-Serov** [pre-commit/pre-commit-hooks#881]
I have this file [CHANGELOG-test.MD](https://github.com/pre-commit/pre-commit-hooks/files/10861542/CHANGELOG-test.MD)
and the following pre-commit hook in the config:
```
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-merge-conflict
```

As you can see, the merge conflict is present, but `pre-commit` reports that everything is fine:
```
> pre-commit run check-merge-conflict --files ./CHANGELOG-test.MD
check for merge conflicts................................................Passed
```

I have tried to play around with hook versions and file filtering
```
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-merge-conflict
    files: ''
    types: [file]
```
but it didn't help.

Does anyone have any idea why it's not caught? I am assuming the file is skipped for some reason, right?
