### ISSUE TITLE
`trailing-whitespace` executable is not the same as the name

### ISSUE THREAD

**Issue by nicolerg** [pre-commit/pre-commit-hooks#887]
I wanted to use hooks installed with `pip install pre-commit-hooks` instead of this git repo. My `.pre-commit-config.yaml` looked like this:
```yaml
repos:
- repo: local
  hooks:
  - id: trailing-whitespace
    name: trailing-whitespace
    stages: [commit]
    entry: trailing-whitespace
    additional_dependencies: [pre-commit-hooks]
    language: python
    types: [file]
...
```
but `pre-commit run --all-files` failed with `Executable 'trailing-whitespace' not found`. Other hooks, like `end-of-file-fixer` and `check-added-large-files`, worked fine. It turns out that the executable for the `trailing-whitespace` hook is actually `training-whitespace-fixer`, so this works:
```yaml
repos:
- repo: local
  hooks:
  - id: trailing-whitespace
    name: trailing-whitespace
    stages: [commit]
    entry: trailing-whitespace-fixer
    additional_dependencies: [pre-commit-hooks]
    language: python
    types: [file]
...
```
Can either the hook name or the executable be changed so they match to avoid this confusion?

pre-commit-hooks version 4.4.0
