### ISSUE TITLE
check-yaml fails on "!reference" used in Gitlab yml(s)

### ISSUE THREAD

**Issue by vainkop** [pre-commit/pre-commit-hooks#890]
Code like this is considered valid & works ok in .gitlab-ci.yml
```
trigger_rule:
  if: '$CI_COMMIT_TAG =~ /^release-([a-zA-Z]+)-v\d+\.\d+\.\d+$/'
  when: always

job:
  rules:
    - !reference [.trigger_rule]
```
[Gitlab docs](https://docs.gitlab.com/ee/ci/yaml/yaml_optimization.html#reference-tags)
  
But the check-yaml fails with
```
could not determine a constructor for the tag '!reference'
```

Excluding .gitlab-ci.yml works but is undesirable.
Any other suggestions?
