### ISSUE TITLE
`types_or: directory` doesn't check submodule changes

### ISSUE THREAD

**Issue by truh** [pre-commit/pre-commit-hooks#893]
You can reproduce the problem by adding a local hook like this

```yaml
-   repo: local
    hooks:
    -   id: submodule-check
        name: submodule check
        entry: submodule check
        language: fail
        types_or: [directory]
```

Adding a submodule

```sh
git submodule add https://github.com/pre-commit/demo-repo.git demo-repo
```

Staging the changes with

```sh
git add .
```

And running pre-commit

```sh
pre-commit run
```

pre-commit will now tell you (or me at least):

```
submodule check......................................(no files to check)Skipped
```

If I use `types` in place of `types_or` the hook fails as expected.

## Version Info

    pre-commit: 2.20.0
    Python 3.10.9
    OS: macOS 12.6
