### ISSUE TITLE
Unrecognized arguments when running locally

### ISSUE THREAD

**Issue by kgrvamsi** [pre-commit/pre-commit-hooks#901]
Hello,

I created a pre-commit hook for cfn guard https://github.com/kgrvamsi/pre-commit-cfnguard and when i try to use the following .pre-commit config locally i see the following issue

.pre-commit-config.yaml
```
  - repo: https://github.com/kgrvamsi/pre-commit-cfnguard
    rev: "v0.0.3"
    hooks:
      - id: cfnguard
        args: 
          [-r, './lib', -t, './lib']
```
Error

```
cfnguard.................................................................Failed
- hook id: cfnguard
- duration: 0.04s
- exit code: 2

usage: cfnguard [-h] -r RULES_LOCATION -t TEMPLATE_LOCATION
cfnguard: error: unrecognized arguments: .pre-commit-config.yaml
```
Not sure where i'm having issue in passing the values, can you please help.
