### ISSUE TITLE
Check for User Story Id in commit message

### ISSUE THREAD

**Issue by suvhotta** [pre-commit/pre-commit-hooks#910]
I've to implement a check in the pre-commit hook that my commit-messages shall always begin with a user story id, similar to the one in the issue: https://github.com/pre-commit/pre-commit-hooks/issues/460

Hence I followed the following steps:

I first installed the pre-commit as:
`
pip3 install pre-commit 
`

Installed the commit-msg hook:
`
pip3 install commit-msg-hook
`

Added the following contents to .pre-commit-config.yaml:
```yaml
repos:
-   repo: local
    hooks:
    -   id: jira-ticket
        name: check for jira ticket
        language: pygrep
        entry: '\A(?![A-Z]+-[0-9]+)'
        args: [--multiline]
        stages: [commit-msg]
```

When I'm committing a file with the message:
```git
git commit -m 'no ticket here'     
```

It is getting committed with the message:
```git
[INFO] Stashing unstaged files to /Users/apple/.cache/pre-commit/patch1685099708-48393.
[INFO] Restored changes from /Users/apple/.cache/pre-commit/patch1685099708-48393.
[main 2a1cabc] no ticket here
 1 file changed, 6 insertions(+)
 create mode 100644 test-pre-commit.py
```

@asottile Could you plz help me here! 
Thank you!
