### ISSUE TITLE
Feature request: Check for RFC 8959 "secret-token" scheme

### ISSUE THREAD

**Issue by Zash** [pre-commit/pre-commit-hooks#940]
[RFC 8959](https://datatracker.ietf.org/doc/html/rfc8959) registers the `secret-token:` URI scheme with the intent of establishing a common syntax for authentication tokens and making it easier to detect tokens and prevent them from leaking into e.g. version control systems.

Seems a natural fit for this project, given it already has checks for private keys and AWS credentials.

**Comment by mxr** [comment]
This can be done with a [pygrep](https://pre-commit.com/#pygrep) hook. Try this as a starting point:

```yaml
-   id: no-secret-token
    name: no secret-token
    description: 'Forbid secret-token:[...] as it is likely a secret'

    # warning - this is untested 
    entry: "secret-token:([A-Za-z0-9-._~!$&'()*+,;=:@]|%[0-9A-Fa-f]{2})+"

    language: pygrep
    types: [text]
```
