### ISSUE TITLE
python tests naming..................................(no files to check)Skipped

### ISSUE THREAD

**Issue by Timo0815** [pre-commit/pre-commit-hooks#963]
Hi together,
this is more a question than a real issue.
I am using some hooks, but have problems only with `name-tests-test`. As shown in the title, no files are found.

my pre-commit-config.yaml:
```
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-added-large-files
  - id: check-ast
  - id: check-case-conflict
  - id: check-merge-conflict
  - id: check-yaml
  - id: debug-statements
  - id: detect-aws-credentials
    args: [--allow-missing-credentials]
  - id: detect-private-key
  - id: double-quote-string-fixer
  - id: end-of-file-fixer
  - id: fix-byte-order-marker
  - id: name-tests-test
    args: [--pytest-test-first]
  - id: no-commit-to-branch
    args: [--branch, develop, --branch, main, --branch, master]
  - id: requirements-txt-fixer
  - id: trailing-whitespace
```

and the console output:
```
(...)$ pre-commit run --all-files
check for added large files..............................................Passed
check python ast.........................................................Passed
check for case conflicts.................................................Passed
check for merge conflicts................................................Passed
check yaml...............................................................Passed
debug statements (python)................................................Passed
detect aws credentials...................................................Passed
detect private key.......................................................Passed
fix double quoted strings................................................Passed
fix end of files.........................................................Passed
fix utf-8 byte order marker..............................................Passed
python tests naming..................................(no files to check)Skipped
don't commit to branch...................................................Passed
fix requirements.txt.....................................................Passed
trim trailing whitespace.................................................Passed
```

In my repo the test files are together with the other files in the same folder, named `test_file.py`
Do I need to change/adapt something, so that the test files are found?

kind regards
