### ISSUE TITLE
`check-executables-have-shebangs` & `check-shebang-scripts-are-executable` not working as expected

### ISSUE THREAD

**Issue by Mo0rBy** [pre-commit/pre-commit-hooks#970]
I have custom shell script hooks in a pre-commit repository. I want to run a pre-commit hook on this repository to check that the shell scripts are executable.

I am running both the `check-executables-have-shebangs` & `check-shebang-scripts-are-executable` hooks to prevent anyone pushing pre-commit shell scripts that are un-runnable.

I created a blank file called `test.sh` which has nothing inside (no shebang line) and has not been made executable `chmod +x`, but both hooks are passing:

![Screenshot 2023-10-04 at 10 04 26](https://github.com/pre-commit/pre-commit-hooks/assets/88185573/bc714a77-ebe3-4cb1-bb12-9073bcf8687c)

![Screenshot 2023-10-04 at 10 06 00](https://github.com/pre-commit/pre-commit-hooks/assets/88185573/6acbc3ae-79d3-449a-86d6-b2c666bf3b27)

All other shell scripts have the shebang line and are executable, so I am only expecting this `test.sh` file to cause a failure. Am i doing something wrong? Am I misunderstanding what these hooks do?

**Comment by asottile** [comment]
you're using an old version and you didn't check in the files

**Comment by Mo0rBy** [comment]
I'm using `v4.4.0` (which is the latest).

I'm not sure what you mean "didn't check in the files". I haven't set any other settings, so the hook should be checking all files.

The short descriptions on the documentation indicate that these hooks should be checking for shebangs in non-binary executables and that non-binary files with shebangs are set to executable:

![Screenshot 2023-10-04 at 13 27 38](https://github.com/pre-commit/pre-commit-hooks/assets/88185573/201bc023-661b-4ad0-bf1e-fb6b491c1e33)

**Comment by asottile** [comment]
I can tell that you're not on the latest version because your screenshot has the hook names capitalized

if your files aren't part of git they aren't being checked

**Comment by Mo0rBy** [comment]
I set the `name:` parameter, thats why they are capitalised.

Here's the relevant part of the `.pre-commit-config.yaml`
```yaml
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        name: Remove trailing whitespaces
      - id: end-of-file-fixer
        name: Check ends of files
      - id: check-merge-conflict
        name: Check for merge-conflicts
      - id: check-yaml
        name: Check for un-parseable yaml
        args: [--allow-multiple-documents]
      - id: check-executables-have-shebangs
        name: Check shell script for shebang lines
      - id: check-shebang-scripts-are-executable
        name: Check shell scripts are executable
```

As I already said, I'm using the latest revision tag, so unless there is a new version that doesn't use tags, then yes, that would be correct.
The `.pre-commit-config.yaml` file is at the root of my git repo. The `.sh` files I want to ensure are valid + executable are in `/.pre-commit-scripts` and they were added and commited. The test file I created successfully got through both these hooks, which doesn't seem right.

**Comment by Mo0rBy** [comment]
Entire config file:
```yaml
---
default_install_hook_types: [pre-commit, commit-msg]
default_stages: [pre-commit]
repos:
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
      - id: gitlint
        name: Check commit message format
        stages: [commit-msg]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        name: Remove trailing whitespaces
      - id: end-of-file-fixer
        name: Check ends of files
      - id: check-merge-conflict
        name: Check for merge-conflicts
      - id: check-yaml
        name: Check for un-parseable yaml
        args: [--allow-multiple-documents]
      - id: check-executables-have-shebangs
        name: Check shell script for shebang lines
      - id: check-shebang-scripts-are-executable
        name: Check shell scripts are executable

  - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
    rev: 0.2.3
    hooks:
      - id: yamlfmt
        args: [--mapping, '2', --sequence, '4', --offset, '2']
        name: Check yaml formatting

  - repo: https://github.com/Lucas-C/pre-commit-hooks-nodejs
    rev: v1.1.2
    hooks:
      - id: markdown-toc

  - repo: local
    hooks:
      - id: kustomize-build
        name: All relevant namespaces must pass 'kustomize build'
        description: This executes 'kustomize build' for all relevant namespaces.
        entry: .pre-commit-scripts/kustomize_build.sh
        language: script
        pass_filenames: false
```

Git repo structure:
![Screenshot 2023-10-04 at 15 08 18](https://github.com/pre-commit/pre-commit-hooks/assets/88185573/008832db-fd0b-45e6-8e7a-add3ea198330)

The `test.sh` file (which should be failing those 2 hooks):
![Screenshot 2023-10-04 at 15 09 46](https://github.com/pre-commit/pre-commit-hooks/assets/88185573/08883e28-aa25-4021-bccf-fc7421b6d786)

Output of `pre-commit run --all-files`:
![Screenshot 2023-10-04 at 15 09 40](https://github.com/pre-commit/pre-commit-hooks/assets/88185573/ae1cb32c-9c81-4269-a24b-a67944481113)
