### ISSUE TITLE
Not compatible with poetry

### ISSUE THREAD

**Issue by Prabhat-Thapa45** [pre-commit/pre-commit-hooks#976]
I was trying to implement pre-commit in our python project, and we are using poetry version 1.1.14.
I tried pre-commit version 2.9.2 to the latest one but still having issues using it. Everytime I try to commit I get an error .

          raise RuntimeError("The Poetry configuration is invalid:\n" + message)
      RuntimeError: The Poetry configuration is invalid:
        - [extras.pipfile_deprecated_finder.2] 'pip-shims<=0.3.4' does not match '^[a-zA-Z-_.0-9]+$'

      [end of output]
I tried to make sure it uses the same poetry version so somewhere I found this for `.pre-commit-config.yaml`
```
repos:
- repo: local
  hooks:
  - id: pre-commit
    name: pre-commit
    language: python
    entry: poetry run pre-commit run --all-files
    stages:
    - commit
```

The issue remains the same. My poetry.lock file has this
```

[package.extras]
colors = ["colorama (>=0.4.3)"]
requirements-deprecated-finder = ["pip-api", "pipreqs"]
pipfile-deprecated-finder = ["pip-shims (>=0.5.2)", "pipreqs", "requirementslib"]
plugins = ["setuptools"]
```  
which is the only direct reference I have with this package pip-shims.
